### ISSUE TITLE
禁用后无法再启动

### ISSUE THREAD

**Issue by hongweipeng** [jzwalk/HighSlide#1]
插件开启后会建表，禁用后重新开启会报`数据表建立失败, 插件启用失败. 错误号: 42S01`。使用版本：1.4.6-rc

**Comment by FlickerMi** [comment]
需要备份之前的表`typecho_gallery`，然后删除表`typecho_gallery`，最后启用插件，导入表。

**Comment by jzwalk** [comment]
报码兼容问题，新版已解决。
